### ISSUE TITLE
ValueError: unichr() arg not in range(0x10000) (narrow Python build)

### ISSUE THREAD

**Issue by banxi1988** [Pythonity/icon-font-to-png#7]
python: 2.7.10 (the macOS builtin Python)
os: macOS 10.11.5
here is my iconfont.css file
[iconfont.css.txt](https://github.com/Pythonity/icon-font-to-png/files/463044/iconfont.css.txt)

``` py
➜  ux_1473385914_8062558 icon-font-to-png --css iconfont.css --ttf iconfont.ttf --size 128
Traceback (most recent call last):
  File "/usr/local/bin/icon-font-to-png", line 16, in <module>
    command_line.run(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/icon_font_to_png/command_line.py", line 97, in run
    keep_prefix=args.keep_prefix)
  File "/Library/Python/2.7/site-packages/icon_font_to_png/icon_font.py", line 24, in __init__
    self.css_icons, self.common_prefix = self.load_css()
  File "/Library/Python/2.7/site-packages/icon_font_to_png/icon_font.py", line 62, in load_css
    icons[name] = unichr(int(val[1:], 16))
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
```

**Comment by pawelad** [comment]
Does it work with Font Awesome ttf and css files?

Also from quick Google'ing:
https://github.com/lambdalisue/e4u/issues/1
https://github.com/HypothesisWorks/hypothesis-python/issues/29

So the quick fix should be to install latest Python via Homebrew, but I'll look into it and try to fix it on the default build in macOS too.
